# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos_6.7"
  config.vm.box_url = "http://10.65.228.71/data/centos6.7/centos6.7.json"

  config.vm.define "db1" do |db1|
    db1.vm.hostname = "db1"
    db1.vm.network "private_network", ip: "192.168.50.101"
  end 

  config.vm.provider "virtualbox" do |v| 
    v.memory = 1024
    v.cpus = 1 
  end 

  config.ssh.password = "vagrant"

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "cookbooks"
    chef.file_cache_path = "chef-solo"
    chef.add_recipe "mariadb"
  end

end
